# Generated by Django 3.0.3 on 2020-02-23 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200222_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='commentText',
            field=models.TextField(max_length=200),
        ),
    ]
