# Generated by Django 3.0.3 on 2020-02-23 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200223_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='commentText',
            field=models.TextField(max_length=100),
        ),
    ]
