# Generated by Django 3.0.3 on 2020-02-23 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200223_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='postId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
        ),
        migrations.AlterField(
            model_name='replys',
            name='postId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
        ),
    ]
