# Generated by Django 3.0.3 on 2020-02-23 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0006_auto_20200223_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='userId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='likes',
            name='like',
            field=models.CharField(choices=[('like', 'like'), ('dislike', 'dislike'), ('none', 'none')], max_length=7),
        ),
        migrations.AlterField(
            model_name='replys',
            name='userId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
