# Generated by Django 3.0.3 on 2020-02-24 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20200224_0403'),
    ]

    operations = [
        migrations.CreateModel(
            name='forbWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forbWord', models.CharField(default='rude', max_length=30)),
            ],
        ),
    ]
