# Generated by Django 3.0.3 on 2020-02-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='subscribe',
            field=models.BooleanField(default=None),
        ),
    ]
