# Generated by Django 3.0.3 on 2020-02-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_subscribe_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='subscribe',
            field=models.BooleanField(default=True),
        ),
    ]
