# Generated by Django 3.0.3 on 2020-02-27 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_forbwords'),
        ('posts', '0011_auto_20200227_1234'),
    ]

    operations = [
    ]
